# Generated by Django 4.1 on 2022-10-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="faqsdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=200)),
                ("answer", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="faqsdata2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=200)),
                ("answer", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="faqsdata3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=200)),
                ("answer", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
