# Generated by Django 4.1 on 2022-10-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luqu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lqxx", name="zkzh", field=models.CharField(max_length=10),
        ),
    ]
